# Generated by Django 5.2.4 on 2025-08-13 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งาน'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'องค์กร', 'verbose_name_plural': 'องค์กร'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_org_admin',
            field=models.BooleanField(default=False, verbose_name='ผู้ดูแลองค์กร'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_platform_admin',
            field=models.BooleanField(default=False, verbose_name='ผู้ดูแลแพลตฟอร์ม'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization', verbose_name='องค์กร'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทธุรกิจ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อองค์กร'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ข้อความแจ้งเตือน')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
    ]
