# Generated by Django 5.2.5 on 2025-08-24 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_platform_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='รหัสสมาชิก'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_org_admin',
            field=models.BooleanField(default=False, verbose_name='เป็นผู้ดูแลองค์กร'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ประเภทธุรกิจ'),
            preserve_default=False,
        ),
    ]
