# Generated by Django 5.2.5 on 2025-08-24 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_platform_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='member_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_platform_admin',
            field=models.BooleanField(default=False, verbose_name='ผู้ดูแลแพลตฟอร์ม'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_org_admin',
            field=models.BooleanField(default=False, verbose_name='ผู้ดูแลองค์กร'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทธุรกิจ'),
        ),
    ]
