# Django settings for project007 project.

# Generated by 'django-admin startproject' using Django 5.2.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/#values


from pathlib import Path
import os # ตรวจสอบให้แน่ใจว่ามีการ import os ที่นี่

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-46kzih05rp!jmjh2^##h)pct1l%8q#(+$s(@#u-yd+kh2(22nvw' # เปลี่ยน key เล็กน้อยเพื่อความปลอดภัย

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # My Apps
    'users.apps.UsersConfig',
    'borrowing.apps.BorrowingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project007.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', # <--- บรรทัดนี้ถูกต้องแล้ว
                'users.context_processors.unread_notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'project007.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# เพิ่มการตั้งค่าสำหรับ Media Files (ไฟล์ที่ผู้ใช้อัปโหลด)
# MEDIA_ROOT คือ path เต็มไปยัง directory บน server ที่จะเก็บไฟล์ที่อัปโหลด
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL คือ URL สาธารณะสำหรับเข้าถึงไฟล์เหล่านี้
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# เพิ่มบรรทัดนี้: บอก Django ให้ใช้ ModelBackend ในการตรวจสอบสิทธิ์
AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',)

# กำหนด URL ที่จะเปลี่ยนเส้นทางหลังล็อกอินสำเร็จ
LOGIN_REDIRECT_URL = 'dashboard' 

# กำหนด URL ที่จะเปลี่ยนเส้นทางหลังล็อกเอาท์สำเร็จ
LOGOUT_REDIRECT_URL = 'login'
