# Generated by Django 5.2.5 on 2025-09-30 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_organization_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='ไอคอน (เช่น fa-laptop)')),
            ],
            options={
                'verbose_name': 'หมวดอุปกรณ์',
                'verbose_name_plural': 'หมวดอุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อประเภทสิ่งของ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='จำนวนทั้งหมด')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='จำนวนที่เหลืออยู่')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='รูปภาพสิ่งของ')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='องค์กร')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='borrowing.itemcategory', verbose_name='หมวดอุปกรณ์')),
            ],
            options={
                'verbose_name': 'ประเภทสิ่งของ',
                'verbose_name_plural': 'ประเภทสิ่งของ',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='หมายเลขซีเรียล')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID อุปกรณ์')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='ตำแหน่ง')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='วันที่เพิ่มเข้าระบบ')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('on_loan', 'กำลังถูกยืม'), ('maintenance', 'บำรุงรักษา'), ('retired', 'ปลดระวาง')], db_index=True, default='available', max_length=20, verbose_name='สถานะ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='borrowing.item', verbose_name='ประเภทสิ่งของ')),
            ],
            options={
                'verbose_name': 'อุปกรณ์',
                'verbose_name_plural': 'อุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำขอ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มใช้ (จอง)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดคืน')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับของจริง')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืน')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติแล้ว/จองสำเร็จ'), ('returned', 'คืนแล้ว'), ('rejected', 'ถูกปฏิเสธ'), ('overdue', 'เกินกำหนด')], db_index=True, default='pending', max_length=20, verbose_name='สถานะ')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผลการยืม')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='borrowing.asset', verbose_name='อุปกรณ์')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม')),
            ],
            options={
                'verbose_name': 'รายการยืม',
                'verbose_name_plural': 'รายการยืม',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('serial_number__isnull', False), ('device_id__isnull', False), _connector='OR'), name='asset_sn_or_deviceid_required'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_item_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['asset', 'status'], name='borrowing_l_asset_i_13de7f_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['asset', 'start_date', 'due_date'], name='borrowing_l_asset_i_e6c999_idx'),
        ),
    ]
