# Generated by Django 5.2.5 on 2025-08-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        ('users', '0002_alter_customuser_options_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'สิ่งของ', 'verbose_name_plural': 'สิ่งของ'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrow_date'], 'verbose_name': 'รายการยืม', 'verbose_name_plural': 'รายการยืม'},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='รูปภาพสิ่งของ'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ประเภทสิ่งของ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='available_quantity',
            field=models.IntegerField(verbose_name='จำนวนที่เหลืออยู่'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อสิ่งของ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='องค์กร'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='จำนวนทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยืม'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(verbose_name='กำหนดคืน'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.item', verbose_name='สิ่งของ'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืน'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติแล้ว'), ('returned', 'คืนแล้ว'), ('rejected', 'ถูกปฏิเสธ'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('organization', 'name')},
        ),
    ]
