# Generated by Django 5.2.5 on 2025-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
