# Generated by Django 5.2.5 on 2025-08-22 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='องค์กร'),
        ),
        migrations.AddField(
            model_name='asset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='borrowing.item', verbose_name='ประเภทสิ่งของ'),
        ),
        migrations.AddField(
            model_name='loan',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.asset', verbose_name='อุปกรณ์ที่ยืม'),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('organization', 'name')},
        ),
    ]
