# Generated by Django 5.2.5 on 2025-09-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_itemcategory_options_alter_itemcategory_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
