# Generated by Django 5.2.5 on 2025-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reason',
            field=models.TextField(blank=True, verbose_name='เหตุผลในการยืม'),
        ),
    ]
