# Generated by Django 5.2.5 on 2025-10-01 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_itemcategory_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='borrowing_l_status_641648_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower'], name='borrowing_l_borrowe_5dfb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='borrowing_l_due_dat_9f2258_idx'),
        ),
    ]
