# Generated by Django 5.2.5 on 2025-08-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_loan_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'อุปกรณ์', 'verbose_name_plural': 'อุปกรณ์'},
        ),
        migrations.AddField(
            model_name='item',
            name='available_quantity',
            field=models.IntegerField(default=0, verbose_name='จำนวนที่เหลืออยู่'),
        ),
        migrations.AddField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='จำนวนทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สภาพ'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID อุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='หมายเลขซีเรียล'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('on_loan', 'กำลังถูกยืม'), ('maintenance', 'บำรุงรักษา'), ('retired', 'ปลดระวาง')], default='available', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='รูปภาพสิ่งของ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ประเภทสิ่งของ'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.asset', verbose_name='อุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reason',
            field=models.TextField(blank=True, verbose_name='เหตุผลการยืม'),
        ),
    ]
