# Generated by Django 5.2.4 on 2025-09-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_asset_options_item_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='condition',
        ),
    ]
